sportssite/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.views.generic import TemplateView
from sportssite.views import app_login_user, login_user, main_page, logouthandler, profile_page, app_checkusername

admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       url(r'^$', view=TemplateView.as_view(template_name='index.html')),
                       # url(r'^sportssite/', include('sportssite.foo.urls')),
                       url(r'^login/', login_user),
                       url(r'^app_login$', app_login_user),
                       url(r'^app_checkusername$', app_checkusername),
                       url(r'^main/', main_page),
                       url(r'^profile/', profile_page),
                       url(r'^plays/', include('sportstab.urls', namespace='plays')),
                       url(r'^logout$', logouthandler),
                       # Uncomment the admin/doc line below to enable admin documentation:
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),
                       url('^activity/', include('actstream.urls')),
)

# if settings.DEBUG:
#     urlpatterns += patterns('',
#                             (r'^media/(?P<path>.*)$', 'django.views.static.serve',
#                              {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
#     )

sportstab/urls.py
from django.conf.urls import patterns, include, url
from sportstab import views

urlpatterns = patterns('',
                       # Examples:
                       url(r'^view_play/(?P<play_id>\d+)$', views.view_play, name='view_play'),
                       url(r'^create_team/$', views.create_team, name='create_team'),
                       url(r'^create_play/$', views.create_play),
                       url(r'^app_get_play/$', views.app_get_play),
                       url(r'^app_get_tags/$', views.app_get_tags),
                       url(r'^app_set_tags/$', views.app_set_tags),
                       url(r'^add_tag/(?P<play_id>\d+)$', views.add_tag, name='add_tag'),
                       url(r'^add_snapshot/(?P<play_id>\d+)$', views.add_snapshot, name='add_snapshot'),
                       url(r'^remove_snapshot/$', views.remove_snapshot, name='remove_snapshot'),
                       url(r'^update_snapshot/$', views.update_snapshot, name='update_snapshot'),
                       url(r'^remove_tag/(?P<play_id>\d+)$', views.remove_tag, name='remove_tag'),
                       url(r'^view_team/(?P<team_id>\d+)$', views.view_team, name='view_team'),
)

templates/base.html
{% load staticfiles %}
<html>
<head>
    {% include  'header.html' %}
    {% block additionalheaders %}
    {% endblock %}
</head>
<body>
<!-- Nav and Banner -->
<header>
    <div style="background: #212121">
        <div class="row">
            <div class="small-2 columns">
                {% if user.is_authenticated %}
                    <a href="/main">
                {% else %}
                    <a href="/">
                {% endif %}
                        <p style="text-align: center; margin-top: 20px">
                            <img src="{% static 'img/logo.png' %}" style="width: 100; "/>
                        </p>
                    </a>
            </div>
            <div class="small-4 columns">
                {% if user.is_authenticated %}
                    <a href="/main">
                {% else %}
                    <a href="/">
                {% endif %}
                    <p class="name" style="margin-top: 20px; margin-left: -30px">SportsTab</p>
                    <p class="subheader" style="font-size: 140%; margin-top: -25px; margin-left: -30px">Communicate Sports</p>
                </a>
            </div>
            {% if user.is_authenticated %}
            <div class="small-2 columns">
                <p style="margin-top: 50px; color: #fff">{{user.first_name}} {{user.last_name}}</p>
            </div>
            {% endif %}
            <div class="small-4 columns">
                <div style="text-align: right; margin-right: 20px; margin-top: 35px; ">

                    {% if not user.is_authenticated %}
                        <a href="/login" class="radius button" style="font-weight: bold;">Login</a>
                    {% else %}
                        <div style="float:right; margin-left: 25px;">
                            <a href="/profile" class="radius button" style="font-weight: bold;">Profile</a>
                            <a href="/logout" class="radius button" style="font-weight: bold;">Logout</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <!-- Main Content Section -->
    {% block content %}

    {% endblock %}
</header>
{% block inbodyscripts %}
{% endblock %}
</body>
<script src="{% static 'js/foundation.min.js' %}"></script>
<script>
    $(function () {
        $(document).foundation();
    });
</script>
{% block scripts %}
{% endblock %}

</html>

templates/header.html
{% load staticfiles %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>SportsTab</title>

<!-- If you are using CSS version, only link these 2 files, you may add app.css to use for your overrides if you like. -->

<link rel="stylesheet" href="{% static 'css/foundation.css' %}">
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
<link href='http://fonts.googleapis.com/css?family=Nunito:700' rel='stylesheet' type='text/css'>
<script src="{% static 'js/vendor/jquery.min.js' %}"></script>
<script src="{% static 'js/fitVids.js' %}"></script>
<link href='http://fonts.googleapis.com/css?family=Capriola' rel='stylesheet' type='text/css'>
<script src="{% static 'js/vendor/modernizr.min.js' %}"></script>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block additionalheaders %}
    <!-- Main Content Section -->
{% endblock %}
{% block content %}
    <div class="row" style="padding-bottom: 40px">
        <div class="large-12 columns">
            <!--
            <div class="fluid-width-video-wrapper" style="height: 545px">
                <iframe src="//player.vimeo.com/video/88318922?title=0&amp;byline=0&amp;portrait=0&amp;badge=0"
                        frameborder="0" webkitallowfullscreen mozallowfullscreen width="1200" height="1000"
                        allowfullscreen></iframe>
            </div>
            !-->
        </div>
    </div>
    <!-- Call to Action Panel -->
    <div class="middle-row">
        <div class="row">
            <div class="large-12 columns">

                <div class="panel">
                    <div class="row">
                        <div class="large-6 columns">
                            <div class="thinglist-iphone animated bounceInLeft">
                                <p><img src="{% static 'img/device-2014-03-11-174124_framed.png' %}"></p>
                            </div>
                        </div>
                        <div class="large-6 columns" style="text-align: center;">
                            <h1 style="color: #999; margin-top: 150px">Revolutionizing Sports Technology</h1>
                            <hr/>
                            <p>SportsTab brings sports into the twenty-first century</p>

                            <a href="#" class="radius button" style="margin-top: 20px">Available on Play Store</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $('#video').fitVids();
    </script>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block additionalheaders %}
    <!-- Main Content Section -->
{% endblock %}
{% block content %}
    <!-- Call to Action Panel -->
    <div class="middle-row">
        <div class="row">
            <div class="large-4 large-centered small-12 columns">
                <div class="panel" style="margin-top: 50%">
                    <h2 style="text-align: center">Sign In</h2>

                    <form action="/login/" method="post" id="login-form">
                        {% csrf_token %}
                        <input type="hidden" value="login" id="type" name="type">
                        <input name="email" placeholder="Email" type="email">
                        <input name="first_name" placeholder="First Name" type="text" class="hide-signup">
                        <input name="last_name" placeholder="Last Name" type="text" class="hide-signup">
                        <input name="password" type="password" placeholder="Password">

                        <div class="row" style="margin-top: 1em">
                            <div class="large-12 columns">
                                <button id="login-button" type="submit" class="button radius">Login</button>
                                <button id="signup-button" type="button" class="button radius">Sign Up</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $(function () {
            var status = 0;
            $('.hide-signup').hide();
            $('#signup-button').click(function () {
                if (status == 0) {
                    $('#login-button').hide();
                    var $hide = $('.hide-signup');
                    $hide.show();
                    $hide.attr('required', "True");
                    $('#type').val('signup');
                    status = 1;
                } else {

                    $('#login-form').submit();
                }
            });
        });
    </script>
{% endblock %}

templates/main.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block additionalheaders %}
    <link rel="stylesheet" href="{% static 'css/chosen.min.css' %}">
{% endblock %}
{% block content %}
    <div class="row" style="min-width: 100%; background: #fff; padding-top: 4%; ">
        <div class="large-12 columns">
            <dl class="tabs vertical" style="padding-left: 0; " data-tab>
                <dd class="active"><a href="#panel1a" style="font-weight: bold;">Home</a></dd>
                <dd><a href="#panel2a" style="font-weight: bold;">Teams</a></dd>
            </dl>
            <div class="tabs-content vertical" style="background: white;">
                <div class="content active" id="panel1a">
                    <div class="small-8 columns">
                        <div style="text-align: center;">
                            <h4 style="color: #990000; padding-bottom: 20px; ">Plays</h4>

                            <div class="row" id="filts">
                                <p style="text-align: left">Filters</p>

                                <div class="small-2 columns">
                                    <span
                                        class="labels selected all">All</span>
                                </div>
                                {% for pref in user.profile.preferred_tags.all %}
                                    <div class="small-2 columns">
                                    <span
                                        class="labels">{{ pref.tag_name }}</span>
                                    </div>
                                {% endfor %}

                            </div>
                            <div class="row" id="plays-list">
                                <div class="small-12 columns">
                                    <input type="text" name="search-terms" class="search"
                                           placeholder="Filter by team or tags">
                                </div>
                                <div class="small-12 columns">
                                    You have {{ plays.count }} plays!
                                    <ul style="list-style: none" class="list">
                                        {% if plays %}
                                            {% for p in plays %}
                                                <li>
                                                    <div class="small-1 columns"
                                                         style="width: 200px; height: 300px;">
                                                        <a href="{% url 'plays:view_play' p.id %}">
                                                            <p class="play-name">{{ p.name }}</p>

                                                            <p class="tags" style="display: none">
                                                                {% for t in p.get_string_tags %}-{{ t }}
                                                                    -{% endfor %}</p>

                                                            <p><img src="/media/{{ p.preview.name }}"/></p>
                                                        </a>
                                                    </div>
                                                </li>
                                            {% endfor %}
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="small-4 columns">
                        <div style="text-align: center;">
                            <h4 style="color: #990000; padding-bottom: 20px; ">Recent Activity</h4>
                            {% for feed in feeds %}
                                <div
                                    class="class_news_item">{{ feed.actor.first_name }} {{ feed.actor.last_name }} {{ feed.verb }}</div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="content" id="panel2a" style="width: 70%;">
                    <div class="row" style="padding-top: 20px; padding-bottom: 10px; ">
                        <div class="small-12 columns" style="text-align: center; ">
                            <dl class="accordion" data-accordion>
                                <dd>
                                    <a href="#panel_join" style="background: white;" onClick="chosen_select();">
                                        <div class="class_team_actions">
                                            Join Team
                                        </div>
                                    </a>

                                    <div id="panel_join" class="content" style="padding: 0;">
                                        {% csrf_token %}
                                        <div class="row">
                                            <select id="team-to-join" name="team-to-join" multiple
                                                    data-placeholder="Select a team"
                                                    class="chosen-select">
                                                {% for team in all_teams %}
                                                    <option value="{{ team }}">
                                                        {{ team.team_name }} by {{ team.manager }}
                                                    </option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <button class="radius button" id="join-team" style="margin-top: 10px">Join
                                        </button>
                                    </div>
                                </dd>
                            </dl>
                        </div>
                    </div>
                    <div class="row" style="padding-top: 10px; padding-bottom: 10px; ">
                        <div class="small-12 columns" style="text-align: center; ">
                            <a href="{% url 'plays:create_team' %}">
                                <div class="class_team_actions">
                                    Create Team
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="row" style="padding-top: 10px; padding-bottom: 10px; ">
                        <div class="small-12 columns" style="text-align: center; ">
                            <dl class="accordion" data-accordion>
                                <dd>
                                    <a href="#panel_edit" style="background: white; padding: 0px; ">
                                        <div class="class_team_actions">
                                            Edit Team
                                        </div>
                                    </a>

                                    <div id="panel_edit" class="content" style="padding: 0px; ">
                                        {% for team in my_teams %}
                                            <a href="{% url 'plays:view_team' team.id %}"
                                               style="background:white; padding: 0;">
                                                <div class="class_team_name">
                                                    {{ team.team_name }}
                                                </div>
                                            </a>
                                        {% endfor %}
                                    </div>
                                </dd>
                            </dl>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block inbodyscripts %}

{% endblock %}
{% block scripts %}
    <script src="{% static 'js/foundation/foundation.tab.js' %}"></script>
    <script src="{% static 'js/foundation/foundation.accordion.js' %}"></script>
    <script src="{% static 'js/chosen.jquery.min.js' %}"></script>
    <script src="{% static 'js/list.js' %}"></script>
    <script>
        function chosen_select() {
            setTimeout(function () {
                $(".chosen-select").chosen();
            }, 100);
        }
        $(function () {
            //$(".chosen-select").chosen();
        });
        var selected_filters = [];
        $('#filts').find('span').click(function () {
            var label = '-' + $(this).text() + '-';
            if (label == "-All-") {
                $('.list').find('li').show();
                $('#filts').find('span').removeClass('selected');
                $(this).addClass('selected');
            } else {
                var $list = $('.list').find('li');
                $('#filts').find('.all').removeClass('selected');
                $(this).toggleClass('selected');
                if ($(this).hasClass('selected')) {
                    selected_filters.push(label);
                } else {
                    $.each(selected_filters, function (i) {
                        if (selected_filters[i] === label) {
                            selected_filters.splice(i, 1);
                            return false;
                        }
                    });
                }
                $list.show();
                $list.each(function (index) {
                    var some = false;
                    for (var i = 0; i < selected_filters.length; i++) {
                        if ($(this).find('.tags').text().indexOf(selected_filters[i]) == -1 && $(this).find('.play-name').text().indexOf(selected_filters[i]) == -1) {
                            some = true;
                            break;
                        }
                    }
                    if (!some) {
                        $(this).hide();
                    }
                });
            }


        });

        function filter() {
            // Go over all images and if tag is not present, make it invisible
        }
        var options = {
            valueNames: [ 'play-name', 'tags' ]
        };

        var list = new List('plays-list', options);
    </script>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block additionalheaders %}
{% endblock %}
{% block content %}
    <div class="row" style="background: #fff; padding-top: 2%; margin-top: 2%" xmlns="http://www.w3.org/1999/html">
        <div class="large-6 columns" style="text-align: center">
            <form action="/profile/" class="dropzone" id="main">
                {% csrf_token %}
                <input type="hidden" name="type" value="pic">
                {% if user.profile.picture %}
                    <img id="profile_im" src="/media/{{ user.get_profile.picture }}">
                {% else %}
                    <img id="profile_im" src="{% static 'img/male_avatar20-512.png' %}">
                {% endif %}

                <div class="fallback">
                    <input name="file" type="file"
                           style="background:{% static 'img/male_avatar20-512.png' %}; width: 512px;height: 512px"/>
                </div>
            </form>

        </div>
        <div class="large-6 columns" style="text-align: left">
            <div class="row">
                <div class="large-12 columns">
                    <h3 style="text-align: center; margin-bottom: 20px">{{ user.first_name }} {{ user.last_name }}</h3>
                </div>
            </div>
            <div class="row">
                <div class="large-12 columns">
                    <p><strong>Favourite Position: </strong><span id="pos-id">{{ user.profile.fav_position }}</span></p>
                </div>
            </div>
            <div class="row">
                <div class="large-12 columns">
                    <p><strong>Affiliation: </strong><span id="aff-id">{{ user.profile.affiliation }}</span>
                </div>
            </div>
            <div class="row">
                <div class="large-12 columns">
                    <button class="radius button right" id="edit">Edit</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/dropzone.js' %}"></script>
    <script>
        $(function () {
            Dropzone.autoDiscover = false;
            var myDropzone = new Dropzone("#main", {'previewTemplate': '<span></span>'});
            myDropzone.on('success', function (res, data) {
                if (parseInt(data['fail']) == 0) {
                    $('#profile_im').attr('src', '/media/' + data['link']);
                }
            });
            var status = 0;

            $('#edit').click(function () {
                var $pos;
                var $aff;
                if (status == 0) {
                    $(this).text('Update');
                    $pos = $('#pos-id');
                    $pos.before("<input type='text' id='pos-id' value='" + $pos.text() + "'>");
                    $pos.remove();
                    $aff = $('#aff-id');
                    $aff.before("<input type='text' id='aff-id' value='" + $aff.text() + "'>");
                    $aff.remove();
                    status = 1;
                } else {
                    $pos = $('#pos-id');
                    $aff = $('#aff-id');
                    $.post('/profile/', {'csrfmiddlewaretoken': $('input[name="csrfmiddlewaretoken"]').val(),
                        'fav-pos': $pos.val(), 'aff': $aff.val(), 'type': 'update'
                    }, function (data) {
                        $pos.before("<span id='pos-id'>" + $pos.val() + "</span>");
                        $pos.remove();
                        $aff.before("<span id='aff-id'>" + $aff.val() + "</span>");
                        $aff.remove();
                        $('#edit').text('Edit');
                    });
                    status = 0;
                }
            });
        });
    </script>
{% endblock %}

templates/teams.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block additionalheaders %}
    <!-- Main Content Section -->
{% endblock %}
{% block content %}
{% endblock %}
{% block scripts %}
    <script>
        $('#video').fitVids();
    </script>
{% endblock %}